clear all; close all; clc
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\conor\Box\NIEHS Hydrogel R01\AIM2_data\O2\ratedata_complete_full_perday.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 25-Jul-2022 17:43:25

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 34);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "B6:AI6";

% Specify column names and types
opts.VariableNames = ["VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
ratedatacompletefullperday = readtable("C:\Users\harrcono\Box\NIEHS Hydrogel R01\AIM2_data\O2\ratedata_complete_full_perday.xlsx", opts, "UseExcel", false);

%% Convert to output type
rates = table2array(ratedatacompletefullperday);

%% Clear temporary variables
clear opts



rates1 = rates(1:17);
rates30 = rates(18:end);
Day = ones(34,1);
Day(18:end) = 30;
Daybox = categorical(Day);
[h,p,ci,stats] = ttest2(rates1,rates30,'Vartype','unequal','Dim',2)
% [p,tbl,stats] = anova1(rates1,rates30)
% daybox = cats(Daybox);
daytrial = ones(2,17);
daytrial(2,1:17) = 2;
for i = 1:length(rates1)
    rateplots(1,i) = rates1(i);
    rateplots(2,i) = rates30(i);
end

figure(1)
hold on
hplot = boxchart(Daybox(1:17),rates1);
hplot.BoxFaceColor = '#005AB5';
hplot.BoxFaceAlpha = 0.4; 
hplot.LineWidth = 2;
hplot.BoxWidth = 0.8;
hplot2 = boxchart(Daybox(18:end),rates30);
hplot2.BoxFaceColor = '#DC3220';
hplot2.BoxFaceAlpha = 0.4; 
hplot2.LineWidth = 2;
hplot2.BoxWidth = 0.8;
plot([1,1],[(max(rateplots(1,:))*1.05) (max(rateplots(1,:))*1.08)],'k-') 
plot([1,2],[(max(rateplots(1,:))*1.08) (max(rateplots(1,:))*1.08)],'k-')
plot([2,2],[(max(rateplots(1,:))*1.08) (max(rateplots(1,:))*1.05-max(rateplots(1,:))+max(rateplots(2,:)))],'k-')
text(mean([1 2]), (max(rateplots(1,:))*1.17), '\ast','FontSize',24)
% h1 = scatter(Day(1:17),rates1,'filled','MarkerEdgeColor','k','LineWidth',1.5,'Jitter',0.5)
% h2 = scatter(Day(1:17)*2,rates30,'filled','MarkerEdgeColor','k','LineWidth',1.5,'Jitter',0.5)
% pl = scatter(daytrial,rateplots,'filled','MarkerEdgeColor','k','LineWidth',1.5,'Jitter',0.5)
pl1 = line(daytrial,rateplots,'MarkerEdgeColor','k','LineWidth',1.5,'Color',[0.7 0.7 0.7 0.5])
pl2 = scatter(daytrial,rateplots,50,'filled','MarkerEdgeColor','k','MarkerFaceColor','#b3b3b3','LineWidth',1.5,'MarkerFaceAlpha',0.5,'MarkerEdgeAlpha',0.7);
ylim([0 50])
% xlim([0 3])
ax = gca;
ax.LineWidth = 3;
xlab = xlabel('\boldmath$\mathsf{Day}$','Interpreter','latex','FontWeight','b');
ylab = ylabel({'';'\boldmath$\mathsf{k_{O_2} \: [\frac{\mu mol \: O_2}{g_{bead} \: d} ]}$'},'Interpreter','latex')
ax.FontSize = 22;
box on
hold off
